### ISSUE TITLE
Please specify license

### ISSUE THREAD

**Issue by agilob** [alexpana/qt-creator-wombat-theme#5]
so I know if I can re-use it in different project.

**Comment by alexpana** [comment]
I've never been good with licenses. Just tell me the least restrictive license, and I'll use that.

**Comment by agilob** [comment]
MIT :)

Thanks.

**Comment by makao95** [comment]
I think Creative Commons licence whout be better for that project. I suggest CC-BY. 
Great theme by the way.

**Comment by alexpana** [comment]
I've added "The Unlicense" license. I would've gone for WTFPL like I usually do, but I've just discovered this one, and why not? All the same to me :)
